[feature] Create example config.json on first run (#73)
* Create example config.json on first run
* Verify output on gha job
* Fix justjoinit scrapper
* Add some tests

diff --git a/.github/workflows/build_run_test.yaml b/.github/workflows/build_run_test.yaml
--- a/.github/workflows/build_run_test.yaml
+++ b/.github/workflows/build_run_test.yaml
@@ -46,7 +46,16 @@ jobs:
 
       - name: Run scrapper
         run: |
-          jobscrapper --config jobscrapper/config.json | tee run.log
+          jobscrapper --config jobscrapper/config.json
+
+      - name: Verify output
+        run: |
+          if grep -q ERROR "debug.log"; then
+            echo "ERROR: Log is containing exception or error!"
+            exit 1
+          else
+            echo "All good"
+          fi
 
       - name: Check if files exists
         run: |
